FROM sabotagecla6/ubuntu-gui-jp

WORKDIR /install

# ***********************************************
# install packages
# ***********************************************
ADD https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb google-chrome-stable.deb

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --install-recommends -y \
        libnspr4 libnss3 libvulkan1 xdg-utils fonts-liberation wget ubuntu-restricted-extras \
        /install/google-chrome-stable.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
