FROM sabotagecla6/vscode

WORKDIR /install

RUN apt-get update -y && sudo apt-get upgrade -y;

# install flutter
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y curl git unzip xz-utils zip libglu1-mesa;
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
      clang cmake git \
      ninja-build pkg-config \
      libgtk-3-dev liblzma-dev \
      libstdc++-12-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /opt/flutter/
ADD https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.44.0-stable.tar.xz flutter_linux-stable.tar.xz
RUN tar -xf flutter_linux-stable.tar.xz -C /opt/
RUN echo 'export PATH="/opt/flutter/bin:$PATH"' >> /etc/.bash_profile    

# ***********************************************
# setting for create user
# ***********************************************
ENV USER_ID=9999
ENV GROUP_ID=9999
ENV USER=installer
ENV NO_PASSWD=true

# ***********************************************
# setting environment for GUI
# ***********************************************
ENV PULSE_COOKIE=/tmp/pulse/cookie
ENV PULSE_SERVER=unix:/tmp/pulse/native
ENV XDG_RUNTIME_DIR=/run/user/${USER_ID}
ENV DBUS_SESSION_BUS_ADDRESS=unix:path=${XDG_RUNTIME_DIR}/bus
ENV XAUTHORITY=/home/${USER}/.Xauthority

RUN /usr/local/bin/create-user.sh

COPY sudo -u installer code --install-extension Dart-Code.flutter
COPY setup-extensions.sh /install/setup-extensions.sh

# RUN /install/setup-extensions.sh


# install android studio
# RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ncurses bzip2;
# ENTRYPOINT ["/usr/bin/entrypoint.sh"]
# CMD ["vscode", "-w"]
