FROM sabotagecla6/vscode

WORKDIR /install

RUN apt-get update -y && sudo apt-get upgrade -y;

# install flutter
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y curl git unzip xz-utils zip libglu1-mesa;
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
      clang cmake git \
      ninja-build pkg-config \
      libgtk-3-dev liblzma-dev \
      libstdc++-12-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /usr/local/flutter/
ADD https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.41.9-stable.tar.xz flutter_linux-stable.tar.xz
RUN tar -xf flutter_linux-stable.tar.xz -C /usr/local/
RUN echo 'export PATH="/usr/local/flutter/bin:$PATH"' >> ~/.bash_profile    

# install android studio
# RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ncurses bzip2;
# ENTRYPOINT ["/usr/bin/entrypoint.sh"]
# CMD ["vscode", "-w"]
