# syntax=docker/dockerfile:1.3-labs

FROM docker.io/library/ubuntu

# ***********************************************
# install packages for xrdp, and do setting
# ***********************************************
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        apt-utils sudo curl bash-completion vim \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

# ***********************************************
# bash complete 
# ***********************************************
RUN mv /etc/apt/sources.list /etc/apt/sources.list.d/sources.list
RUN cp -p /etc/apt/apt.conf.d/docker-clean /etc/apt/apt.conf.d/docker-clean.bk
RUN sed -e "s/^/#/g" /etc/apt/apt.conf.d/docker-clean.bk > /etc/apt/apt.conf.d/docker-clean 

RUN echo "if [ -f /etc/bash_completion ] && ! shopt -oq posix; then" >> /root/.bashrc
RUN echo "    . /etc/bash_completion" >> /root/.bashrc
RUN echo "fi" >> /root/.bashrc
