FROM sabotagecla6/ubuntu-usr

# ***********************************************
# install wine
# ***********************************************
RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y \
        zenity x11-apps \
        pulseaudio

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod a+x /usr/bin/entrypoint.sh

# ENTRYPOINT ["/usr/bin/entrypoint.sh"]
