FROM sabotagecla6/ubuntu-usr

# ***********************************************
# install wine
# ***********************************************
RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install --install-recommends -y \
        zenity x11-apps pulseaudio \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

ENV PULSE_COOKIE=/tmp/pulse/
ENV PULSE_SERVER=unix:/tmp/pulse/native

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod a+x /usr/local/bin/entrypoint.sh

